name: School of Life Daily Post Agent

on:
  schedule:
    # اجرا در ساعت ۱۷:۳۰ UTC (۹ شب به وقت ایران)
    - cron: '30 17 * * *'
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه نوشتن در ریپازیتوری برای ذخیره حافظه

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the agent
        env:
          AVALAI_API_KEY: ${{ secrets.AVALAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python agent.py

      - name: Commit and push memory file (if it exists)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          if [ -f _posted_articles.txt ]; then
            git add _posted_articles.txt
            if ! git diff --staged --quiet; then
              git commit -m "Update posted articles list"
              git push
            else
              echo "No new articles processed. No commit needed."
            fi
          else
            echo "Memory file not found. Skipping commit."
          fi
