name: School of Life Daily Post Agent

on:
  schedule:
    # اجرا در ساعت ۱۷:۳۰ UTC (۹ شب به وقت ایران)
    - cron: '30 17 * * *'
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the agent
        env:
          AVALAI_API_KEY: ${{ secrets.AVALAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python agent.py

      # --- FIX: Make the commit step smarter ---
      - name: Commit and push memory file (if it exists)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # Check if the memory file exists first
          if [ -f _last_processed_link.txt ]; then
            git add _last_processed_link.txt
            if ! git diff --staged --quiet; then
              git commit -m "Update last processed article link"
              git push
            else
              echo "Memory file exists, but no new article was processed. No commit needed."
            fi
          else
            echo "Memory file not found (agent likely failed to summarize). Skipping commit."
          fi
